# Generated by Django 3.2.4 on 2021-06-16 04:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210616_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
