# Generated by Django 3.2.4 on 2021-06-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210616_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='categories',
            field=models.ManyToManyField(related_name='article', to='news.CategoriesModel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
